apiVersion: v1
kind: Service
metadata:
  name: ipfs
spec:
  type: ClusterIP
  selector:
    app: ipfs
  ports:
    - name: "swarm"
      port: 4001
      protocol: TCP
    - name: "api"
      port: 5001
      protocol: TCP
    - name: "gateway"
      port: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  labels:
    name: ipfs
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: {{ .Values.ipfs.image }}:{{ .Values.ipfs.imageVersion }}
        # command: ["/usr/local/bin/start_ipfs"]
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
        - containerPort: 8080
          name: "gateway"
          protocol: "TCP"
