apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    component: app
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}:{{ .Values.app.imageVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
      - name: aws-ecr-key
