apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  type: LoadBalancer
  selector:
    component: blockchain
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      component: blockchain
  template:
    metadata:
      labels:
        component: blockchain
    spec:
      containers:
        - name: blockchain
          image: 817932929274.dkr.ecr.us-east-1.amazonaws.com/blockchain-node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
      imagePullSecrets:
      - name: aws-ecr-key
