apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    component: app
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      {{ if ne .Values.env "dev" }}
      serviceAccountName: eks-dynamodb
      {{ end }}
      containers:
      - name: app
        image: {{ .Values.app.image }}:{{ .Values.app.imageVersion }}
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        # volumeMounts:
        # - name: env-volume
        #   mountPath: /usr/src/app/.env.local
        #   subPath: .env.local
          # readOnly: true
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        readinessProbe:
          exec:
            command:
            - test
            - -f
            - README.md
      # volumes:
      # - name: env-volume
      #   configMap:
      #     name: app-env
      #     defaultMode: 420
      #     items:
      #     - key: .env.local
      #       path: .env.local
      imagePullSecrets:
      - name: aws-ecr-key
