apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
spec:
  type: ClusterIP
  selector:
    app: dynamodb-local
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
  labels:
    name: dynamodb-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
      - name: dynamodb-local
        image: amazon/dynamodb-local:latest
        # command: ["-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: example-claim
